package com.mgw.member;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TOP_USER.
 */
public class TopUser {

    private Long id;
    /** Not-null value. */
    private String joinTime;
    /** Not-null value. */
    private String userName;
    private Integer isGroup;

    public TopUser() {
    }

    public TopUser(Long id) {
        this.id = id;
    }

    public TopUser(Long id, String joinTime, String userName, Integer isGroup) {
        this.id = id;
        this.joinTime = joinTime;
        this.userName = userName;
        this.isGroup = isGroup;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getJoinTime() {
        return joinTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setJoinTime(String joinTime) {
        this.joinTime = joinTime;
    }

    /** Not-null value. */
    public String getUserName() {
        return userName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Integer getIsGroup() {
        return isGroup;
    }

    public void setIsGroup(Integer isGroup) {
        this.isGroup = isGroup;
    }

}
