package com.mgw.member;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table REMEMBER_LOGIN_NAME.
 */
public class RememberLoginName {

    private Long id;
    /** Not-null value. */
    private String loginUserName;
    /** Not-null value. */
    private String loginPassword;
    private boolean isRemember;
    private java.util.Date lastUseTime;

    public RememberLoginName() {
    }

    public RememberLoginName(Long id) {
        this.id = id;
    }

    public RememberLoginName(Long id, String loginUserName, String loginPassword, boolean isRemember, java.util.Date lastUseTime) {
        this.id = id;
        this.loginUserName = loginUserName;
        this.loginPassword = loginPassword;
        this.isRemember = isRemember;
        this.lastUseTime = lastUseTime;
    }
    public RememberLoginName(String loginUserName, String loginPassword, java.util.Date lastUseTime ,boolean isRemember) {
    	this.loginUserName = loginUserName;
    	this.loginPassword = loginPassword;
    	this.isRemember = isRemember;
    	this.lastUseTime = lastUseTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getLoginUserName() {
        return loginUserName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLoginUserName(String loginUserName) {
        this.loginUserName = loginUserName;
    }

    /** Not-null value. */
    public String getLoginPassword() {
        return loginPassword;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword;
    }

    public boolean getIsRemember() {
        return isRemember;
    }

    public void setIsRemember(boolean isRemember) {
        this.isRemember = isRemember;
    }

    public java.util.Date getLastUseTime() {
        return lastUseTime;
    }

    public void setLastUseTime(java.util.Date lastUseTime) {
        this.lastUseTime = lastUseTime;
    }

}
